### PR TITLE
Improve Travis configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
Going through the whole config, improving everything: consistency, readability, fix problems.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could we run on NodeJS 12?

**Comment by acobster** [comment]
Yes, feel free to upgrade Lando and the node version.

**Comment by acobster** [comment]
FYI @szepeviktor I'm considering replacing the whole Cypress suite with `WP_UnitTestCase`s over on #119, like we have in Timber. End-to-end is just the wrong level of abstraction for this, I think. So I wouldn't worry too much about running Lando in CI going forward.

**Comment by szepeviktor** [comment]
Okay, I leave this PR up to you.

**Comment by acobster** [comment]
Good enough for rock 'n' roll. We will need to follow up and fix doc builds but these improvements are useful on their own for now.

**Pull request merged**
