### PR TITLE
Feature/shortcode authorization update

### PR DESCRIPTION
**Pull request by dknoben**
**Ticket**: #19 

#### Issue
Review and update the Shortcode Authorization Class

#### Solution

I reviewed the code, and implemented a small change to how the Shortcode Policy class is implemented so it accepts a tag name so we do not have to hard code the name of the shortcode tag in the UserRoleShortcodePolicy class.  

#### Testing
The ShortcodeAuthorizationPolicyTest has been updated to reflect the change in the Shortcode Policy class.

### CODE REVIEW

**Comment by acobster** [comment]
@dknoben looks like there were some merge conflicts. Can you resolve your branch against master and push again?

**Comment by dknoben** [comment]
Merge conflicts resolved.

**Comment by acobster** [comment]
@dknoben this is looking good, there are just a few coding standards issues to take care of. "All checks have failed" because Travis is running code sniffer tests. Run `lando sniff` to find out what it's complaining about. I think you can run `lando php vendor/bin/phpcbf` to fix most of the issues automatically.

Good to go after that, thanks again!

**Comment by acobster** [comment]
Hey @dknoben - `phpcbf` was able to fix almost all the issues, so don't worry about the issues you were having with codesniffer for now. Let's discuss later.

**Pull request merged**
