### PR TITLE
Issue #103 - Lando rc.2 dev environment. 

### PR DESCRIPTION
**Pull request by kfoubert**
**Ticket**: #103  

#### Issue

Update lando dev environment to work with Lando rc.2

#### Solution

- Followed [these steps](https://docs.devwithlando.io/guides/updating-to-rc2.html) to get Conifer's dev environment up to speed.
- Released (coby) a new build of the custom sitecrafting/lando-cypress-wordpress:latest image for the cypress image based on the new Lando/bitnami image
- Separate the node service out into independent cypress, gitbook, and node containers. Please verify this was done correctly.
- Update the cypress container to use the latest lando-cypress-wordpress image
- Update any overrides blocks to the proper rc.2+ syntax
- Also updated yaml and removed global references. See [Global Environment Variables](https://docs.lando.dev/guides/updating-to-rc2.html#global-environment-variables)
- Update service versions (e.g. the node service) to the latest and greatest. 
  - Using node10. Other services remained the same, based on suggested versions on Lando's website.

#### Impact

Impacts developers local environment. Allows Conifer to run on Lando 3.00 rc.2 .

#### Considerations

Developers can use .lando.old.yml if they are on a previous version of Lando.

#### Testing

Lando Start or Lando Rebuild should complete successfully.

### CODE REVIEW

**Comment by acobster** [comment]
@kfoubert for some reason, automated builds are failing on Travis CI when building the docs. All your changes look good locally but I'm going to have to figure this out before merging this in. If you're able to look at it, that would be great too.

Notes:
* What's failing is the "Building docs" task within Travis CI. The [setup-wordpress.sh](https://github.com/sitecrafting/conifer/blob/master/scripts/setup-wordpress.sh#L26) script is supposed to check for the `CI` variable and, it it's set, it's supposed to skip prompting the user for any input, otherwise the build will just hang and eventually fail. That's exactly what's happening [here](https://travis-ci.org/sitecrafting/conifer/jobs/588698416#L558), as opposed to the Cypress test suite job, which is running correctly [here](https://travis-ci.org/sitecrafting/conifer/jobs/588698415#L576) as part of the same build. Not sure why there's a difference at all; this is supposed to be a Travis CI internal...

**Comment by kfoubert** [comment]
Thanks @acobster !

**Comment by acobster** [comment]
@kfoubert looks like the [broke](https://travis-ci.org/sitecrafting/conifer/jobs/642516760?utm_medium=notification&utm_source=github_status) Cypress tests. I'm able to repro on this branch with `lando e2e`. This might be an issue with the Lando service or with the [`lando-node-cypress`](https://github.com/sitecrafting/lando-node-cypress) image itself. Can you take a look?

**Comment by kfoubert** [comment]
@acobster I think I fixed it by tweaking the .lando.yml file.

groot-lando-e2e

**Comment by acobster** [comment]
@kfoubert it's fixed locally for me too, but it's still failing in CI. I need to look at why...at some point. We'll get there!

**Comment by kfoubert** [comment]
Lame!

**Comment by acobster** [comment]
@kfoubert looking good now. Travis was installing an old Lando version, plus there was some bad data in the cache.

**Pull request merged**
